"""
R3D Agent -- GRC Mapper Module
Translates technical findings into compliance language.
Maps every finding to relevant frameworks based on org type.

Organization types and frameworks loaded:
    personal            CIS Controls + AI RMF (if AI found)
    small_business      CIS Controls + NIST 800-53 + AI RMF
    enterprise          NIST 800-53 + ISO 27001 + AI RMF
    critical_infrastructure  NERC CIP + NIST 800-53 + AI RMF
    all                 Everything above

AI RMF loads automatically if AI surfaces were found
regardless of org type -- any org with AI exposure
gets AI governance mapping.

Org type saved to OSINTProfile -- asked once per engagement.
On resume (--resume flag) org type read from saved profile.

Outputs:
    1. Risk Register XLSX      -- one row per finding
    2. Compliance Map XLSX     -- one sheet per framework
    3. Executive Summary       -- plain English PDF section
                                  generated by Ollama

Performance:
    Lookup table operations -- fast
    Ollama executive summary -- 30-60 seconds
    Total: 1-2 minutes per engagement

Error handling:
    Each output independent -- one failure never stops others
    Missing KB files degrade gracefully
    Ollama failure falls back to template summary
    Excel sheet names sanitized -- no illegal characters

Compatibility: Windows 10/11, Ubuntu, Kali Linux
"""

import re
from datetime import datetime, timedelta
from pathlib import Path
from typing import Optional
from rich.console import Console
from rich.panel import Panel
import pandas as pd

from core.findings import AggregatedFindings, Finding, FindingsAggregator
from core.grc_constants import NIST_MAPPING, NERC_CIP_MAPPING
from core.llm_client import query_llm, LLMResponse

console = Console()

# Paths
BASE_DIR    = Path(__file__).parent.parent
DATA_DIR    = BASE_DIR / "data"
KB_DIR      = DATA_DIR / "compliance_kb"
OUTPUT_DIR  = BASE_DIR / "output"
REPORTS_DIR = OUTPUT_DIR / "reports"

# KB file paths
KB_NIST_800_53 = KB_DIR / "nist_800_53_controls.md"
KB_NERC_CIP    = KB_DIR / "nerc_cip_standards.md"
KB_CIS         = KB_DIR / "cis_controls_v8.md"
KB_ISO_27001   = KB_DIR / "iso_27001_annex_a.md"
KB_AI_RMF      = KB_DIR / "nist_ai_rmf.md"

# Framework loading by org type
ORG_FRAMEWORK_MAP = {
    "personal": [
        "cis_controls",
    ],
    "small_business": [
        "cis_controls",
        "nist_800_53",
    ],
    "enterprise": [
        "nist_800_53",
        "iso_27001",
    ],
    "critical_infrastructure": [
        "nerc_cip",
        "nist_800_53",
    ],
    "all": [
        "cis_controls",
        "nist_800_53",
        "iso_27001",
        "nerc_cip",
        "nist_ai_rmf",
    ]
}

# Framework KB file map
FRAMEWORK_KB_MAP = {
    "nist_800_53":  KB_NIST_800_53,
    "nerc_cip":     KB_NERC_CIP,
    "cis_controls": KB_CIS,
    "iso_27001":    KB_ISO_27001,
    "nist_ai_rmf":  KB_AI_RMF,
}

# Framework display names
# Note: No colons -- Excel sheet names cannot contain ':'
FRAMEWORK_NAMES = {
    "nist_800_53":  "NIST SP 800-53 Rev 5",
    "nerc_cip":     "NERC CIP",
    "cis_controls": "CIS Controls v8",
    "iso_27001":    "ISO 27001 2022",
    "nist_ai_rmf":  "NIST AI RMF 1.0",
}

# NIST_MAPPING and NERC_CIP_MAPPING imported from core.grc_constants
# (single source of truth shared with report_gen.py)

# CIS Controls mapping
CIS_MAPPING = {
    "prompt_injection":     ["Control 16", "Control 7"],
    "jailbreak":            ["Control 16", "Control 18"],
    "trust_escalation":     ["Control 6", "Control 14"],
    "context_manipulation": ["Control 16", "Control 8"],
    "data_exfiltration":    ["Control 3", "Control 11"],
    "crescendo_attack":     ["Control 14", "Control 16"],
    "zero_day":             ["Control 7", "Control 11"],
    "cve_match":            ["Control 7", "Control 2"],
    "exposed_admin":        ["Control 4", "Control 6"],
    "outdated_ssl":         ["Control 4", "Control 7"],
    "exposed_port":         ["Control 4", "Control 12"],
    "header_missing":       ["Control 4", "Control 16"],
    "subdomain":            ["Control 1", "Control 12"],
    "ai_surface":           ["Control 1", "Control 13"],
    "email_exposed":        ["Control 3", "Control 9"],
    "username_exposed":     ["Control 5", "Control 14"],
    "tech_stack":           ["Control 2", "Control 15"],
    "credential_stuffing":  ["Control 5", "Control 9"],
    "default":              ["Control 4", "Control 7"],
}

# ISO 27001 mapping
ISO_MAPPING = {
    "prompt_injection":     ["D.8.26", "D.8.25"],
    "jailbreak":            ["D.8.26", "D.8.29"],
    "trust_escalation":     ["A.5.15", "D.8.2"],
    "context_manipulation": ["D.8.26", "D.8.28"],
    "data_exfiltration":    ["D.8.12", "A.5.14"],
    "crescendo_attack":     ["B.6.3", "D.8.26"],
    "zero_day":             ["D.8.8", "A.5.25"],
    "cve_match":            ["D.8.8", "D.8.9"],
    "exposed_admin":        ["A.5.15", "D.8.2"],
    "outdated_ssl":         ["D.8.24", "D.8.9"],
    "exposed_port":         ["D.8.20", "D.8.22"],
    "header_missing":       ["D.8.9", "D.8.27"],
    "subdomain":            ["D.8.20", "A.5.1"],
    "ai_surface":           ["A.5.23", "D.8.3"],
    "email_exposed":        ["D.8.12", "B.6.1"],
    "username_exposed":     ["A.5.16", "B.6.1"],
    "tech_stack":           ["D.8.9", "A.5.19"],
    "credential_stuffing":  ["D.8.5", "A.5.17"],
    "default":              ["D.8.9", "A.5.1"],
}

# AI RMF mapping
AI_RMF_MAPPING = {
    "prompt_injection":     ["GOVERN 1.4", "MAP 2.1",
                             "MEASURE 2.1", "MANAGE 1.1"],
    "jailbreak":            ["GOVERN 1.4", "MAP 2.1",
                             "MEASURE 2.2", "MANAGE 1.1"],
    "trust_escalation":     ["GOVERN 2.2", "MAP 2.2",
                             "MEASURE 2.3", "MANAGE 1.1"],
    "context_manipulation": ["GOVERN 1.4", "MAP 2.2",
                             "MEASURE 2.2", "MANAGE 1.2"],
    "data_exfiltration":    ["GOVERN 1.5", "MAP 3.1",
                             "MEASURE 2.10", "MANAGE 3.2"],
    "crescendo_attack":     ["GOVERN 2.2", "MAP 2.2",
                             "MEASURE 2.3", "MANAGE 1.1"],
    "ai_surface":           ["GOVERN 1.1", "MAP 1.1",
                             "MEASURE 1.1", "MANAGE 4.1"],
    "default":              ["GOVERN 1.4", "MAP 1.5",
                             "MEASURE 2.2", "MANAGE 1.1"],
}

# Due date by severity
DUE_DATE_MAP = {
    "CRITICAL": 1,
    "HIGH":     30,
    "MEDIUM":   90,
    "LOW":      180,
    "INFO":     365,
}


# ------------------------------------------------------------------ #
# HELPERS
# ------------------------------------------------------------------ #

def _sanitize_filename(value: str) -> str:
    """Safe filename component. No illegal chars."""
    return re.sub(r'[^a-zA-Z0-9_\-]', '_', value)[:30]


def _sanitize_sheet_name(value: str) -> str:
    """
    Sanitize Excel sheet name.
    Excel forbids: \\ / ? * [ ] :
    Max 31 characters.
    """
    sanitized = re.sub(r'[\\/?*\[\]:]', ' ', value)
    return sanitized[:31].strip()


def _load_kb_file(path: Path) -> str:
    """Load KB file. Returns empty string on failure."""
    try:
        if path.exists():
            with open(path, encoding="utf-8") as f:
                return f.read()
    except Exception as e:
        console.print(
            f"[yellow]  KB load failed ({path.name}): "
            f"{e}[/yellow]"
        )
    return ""


def _get_due_date(severity_label: str) -> str:
    """Calculate due date from severity label."""
    days = DUE_DATE_MAP.get(severity_label, 180)
    due  = datetime.now() + timedelta(days=days)
    return due.strftime("%Y-%m-%d")


def _get_framework_controls(
    finding_type: str,
    frameworks:   list[str]
) -> dict:
    """
    Get all applicable controls for a finding
    across all loaded frameworks.
    Returns dict of framework display name -> controls list.
    """
    controls = {}

    if "nist_800_53" in frameworks:
        controls["NIST 800-53"] = NIST_MAPPING.get(
            finding_type, NIST_MAPPING["default"]
        )
    if "nerc_cip" in frameworks:
        controls["NERC CIP"] = NERC_CIP_MAPPING.get(
            finding_type, NERC_CIP_MAPPING["default"]
        )
    if "cis_controls" in frameworks:
        controls["CIS Controls"] = CIS_MAPPING.get(
            finding_type, CIS_MAPPING["default"]
        )
    if "iso_27001" in frameworks:
        controls["ISO 27001"] = ISO_MAPPING.get(
            finding_type, ISO_MAPPING["default"]
        )
    if "nist_ai_rmf" in frameworks:
        controls["NIST AI RMF"] = AI_RMF_MAPPING.get(
            finding_type, AI_RMF_MAPPING["default"]
        )

    return controls


# ------------------------------------------------------------------ #
# GRC MAPPER
# ------------------------------------------------------------------ #

class GRCMapper:
    """
    GRC compliance mapping module.

    Takes aggregated findings and maps them to compliance
    frameworks based on organization type.

    Org type selected once and saved to OSINTProfile.
    AI RMF loaded automatically if AI surfaces found.

    Each output independent -- one failure never stops others.
    Excel sheet names sanitized -- no illegal characters.
    """

    def __init__(
        self,
        target: str,
        mode:   str = "SEMI-AUTO",
    ):
        self.target     = target
        self.mode       = mode.upper()
        self.org_type   = None
        self.frameworks: list[str] = []
        REPORTS_DIR.mkdir(parents=True, exist_ok=True)

    def select_org_type(
        self, saved_org_type: Optional[str] = None
    ) -> str:
        """
        Show org type selection menu.
        Skips menu if org_type already saved to profile.
        while True loop -- exits only on valid input 1-5.
        """
        if saved_org_type:
            console.print(
                f"[dim]  Organization type: "
                f"{saved_org_type} "
                f"(from profile)[/dim]"
            )
            return saved_org_type

        console.print(
            Panel(
                "[bold]Select your organization type:"
                "[/bold]\n\n"
                "[cyan][1][/cyan] Personal / Researcher\n"
                "    CIS Controls + AI RMF (if AI found)\n\n"
                "[cyan][2][/cyan] Small Business\n"
                "    CIS Controls + NIST 800-53\n\n"
                "[cyan][3][/cyan] Enterprise\n"
                "    NIST 800-53 + ISO 27001\n\n"
                "[cyan][4][/cyan] Critical Infrastructure\n"
                "    NERC CIP + NIST 800-53 + AI RMF\n\n"
                "[cyan][5][/cyan] All Frameworks\n"
                "    Everything above",
                title=(
                    "[bold cyan]"
                    "R3D -- Organization Profile"
                    "[/bold cyan]"
                ),
                border_style="cyan"
            )
        )

        org_map = {
            "1": "personal",
            "2": "small_business",
            "3": "enterprise",
            "4": "critical_infrastructure",
            "5": "all",
        }

        while True:
            try:
                choice = input("\nSelect [1-5]: ").strip()
            except EOFError:
                # Non-interactive mode (stdin piped/exhausted) --
                # default to Personal/Researcher
                console.print(
                    "[yellow]  Non-interactive mode — "
                    "defaulting to Personal/Researcher[/yellow]\n"
                    "[dim]  Tip: pass --org-type to skip this "
                    "menu (e.g. --org-type enterprise)[/dim]"
                )
                return "personal"
            if choice in org_map:
                org_type = org_map[choice]
                console.print(
                    f"[green]  Selected: "
                    f"{org_type.replace('_', ' ').title()}"
                    f"[/green]"
                )
                return org_type
            console.print(
                "[yellow]  Invalid. Enter 1, 2, 3, 4, "
                "or 5.[/yellow]"
            )

    def load_frameworks(
        self,
        org_type: str,
        has_ai:   bool = False
    ) -> list[str]:
        """
        Load relevant frameworks for org type.
        AI RMF added automatically if AI surfaces found.
        Skips frameworks with missing KB files.
        """
        frameworks = list(
            ORG_FRAMEWORK_MAP.get(org_type, ["cis_controls"])
        )

        # AI RMF auto-loads if AI surfaces found
        if has_ai and "nist_ai_rmf" not in frameworks:
            frameworks.append("nist_ai_rmf")
            console.print(
                "[dim]  AI surfaces detected -- "
                "NIST AI RMF added[/dim]"
            )

        # Only load frameworks with KB files on disk
        available = []
        for fw in frameworks:
            kb_path = FRAMEWORK_KB_MAP.get(fw)
            if kb_path and kb_path.exists():
                available.append(fw)
                console.print(
                    f"[dim]  Loaded: "
                    f"{FRAMEWORK_NAMES.get(fw, fw)}[/dim]"
                )
            else:
                console.print(
                    f"[yellow]  KB missing: {fw} -- "
                    f"skipping[/yellow]"
                )

        return available

    # ------------------------------------------------------------------ #
    # OUTPUT 1 -- RISK REGISTER
    # ------------------------------------------------------------------ #

    def generate_risk_register(
        self,
        aggregated: AggregatedFindings,
        frameworks: list[str]
    ) -> Optional[str]:
        """
        Generate risk register XLSX.
        One row per finding with all framework controls,
        calculated due dates, owner and status fields.
        Full try/except -- returns None on failure.
        """
        console.print(
            "[cyan]  Generating risk register...[/cyan]"
        )

        try:
            rows = []
            for finding in aggregated.findings:
                controls = _get_framework_controls(
                    finding.finding_type, frameworks
                )

                rows.append({
                    "Finding ID":    finding.id,
                    "Title":         finding.title,
                    "Severity":      finding.severity_label,
                    "Score":         finding.severity_score,
                    "Module":        finding.source_module,
                    "Finding Type":  finding.finding_type,
                    "Description":   finding.description,
                    "MITRE":         finding.mitre_technique,
                    "MITRE Name":    finding.mitre_technique_name,
                    "OWASP":         finding.owasp_category,
                    "OWASP Name":    finding.owasp_category_name,
                    "NIST 800-53":   " · ".join(
                        controls.get("NIST 800-53", [])
                    ),
                    "NERC CIP":      " · ".join(
                        controls.get("NERC CIP", [])
                    ),
                    "CIS Controls":  " · ".join(
                        controls.get("CIS Controls", [])
                    ),
                    "ISO 27001":     " · ".join(
                        controls.get("ISO 27001", [])
                    ),
                    "NIST AI RMF":   " · ".join(
                        controls.get("NIST AI RMF", [])
                    ),
                    "CVE ID":        finding.cve_id or "",
                    "CVSS Score":    finding.cvss_score or "",
                    "Zero Day":      (
                        "YES" if finding.zero_day_flag
                        else "NO"
                    ),
                    "Due Date":      _get_due_date(
                        finding.severity_label
                    ),
                    "Owner":         "TBD",
                    "Status":        "Open",
                    "Target":        finding.target,
                    "Timestamp":     finding.timestamp,
                })

            df = pd.DataFrame(rows)

            safe_target = _sanitize_filename(self.target)
            timestamp   = datetime.now().strftime(
                "%Y-%m-%d_%H-%M-%S"
            )
            xlsx_path = (
                REPORTS_DIR /
                f"{timestamp}_{safe_target}"
                f"_risk_register.xlsx"
            )

            with pd.ExcelWriter(
                str(xlsx_path), engine="openpyxl"
            ) as writer:
                df.to_excel(
                    writer,
                    index=False,
                    sheet_name="Risk Register"
                )
                ws = writer.sheets["Risk Register"]
                for col in ws.columns:
                    max_len = max(
                        len(str(cell.value))
                        if cell.value is not None else 0
                        for cell in col
                    )
                    ws.column_dimensions[
                        col[0].column_letter
                    ].width = min(max_len + 4, 60)

            console.print(
                f"[green]  Risk register: "
                f"{xlsx_path}[/green]"
            )
            return str(xlsx_path)

        except Exception as e:
            console.print(
                f"[red]  Risk register failed: {e}[/red]"
            )
            return None

    # ------------------------------------------------------------------ #
    # OUTPUT 2 -- COMPLIANCE MAP
    # ------------------------------------------------------------------ #

    def generate_compliance_map(
        self,
        aggregated: AggregatedFindings,
        frameworks: list[str]
    ) -> Optional[str]:
        """
        Generate compliance map XLSX.
        One sheet per framework.
        Sheet names sanitized -- no illegal Excel chars.
        Full try/except -- returns None on failure.
        """
        console.print(
            "[cyan]  Generating compliance map...[/cyan]"
        )

        try:
            safe_target = _sanitize_filename(self.target)
            timestamp   = datetime.now().strftime(
                "%Y-%m-%d_%H-%M-%S"
            )
            xlsx_path = (
                REPORTS_DIR /
                f"{timestamp}_{safe_target}"
                f"_compliance_map.xlsx"
            )

            with pd.ExcelWriter(
                str(xlsx_path), engine="openpyxl"
            ) as writer:

                for framework in frameworks:
                    fw_name = FRAMEWORK_NAMES.get(
                        framework, framework
                    )
                    rows = []

                    for finding in aggregated.findings:
                        controls = _get_framework_controls(
                            finding.finding_type, [framework]
                        )
                        fw_controls = list(
                            controls.values()
                        )
                        if not fw_controls:
                            continue

                        control_str = " · ".join(
                            fw_controls[0]
                            if fw_controls else []
                        )

                        gap_status = (
                            "Missing"
                            if finding.severity_label in [
                                "CRITICAL", "HIGH"
                            ]
                            else "Partial"
                            if finding.severity_label == "MEDIUM"
                            else "Needs Review"
                        )

                        rows.append({
                            "Control(s)":   control_str,
                            "Finding":      finding.title,
                            "Severity":     finding.severity_label,
                            "Score":        finding.severity_score,
                            "Gap Status":   gap_status,
                            "Type":         finding.finding_type,
                            "Description":  finding.description[:200],
                            "Due Date":     _get_due_date(
                                finding.severity_label
                            ),
                            "Remediation":  (
                                finding.remediation or
                                "See risk register"
                            ),
                        })

                    if not rows:
                        continue

                    df = pd.DataFrame(rows)

                    # Sanitize sheet name -- no illegal chars
                    sheet_name = _sanitize_sheet_name(
                        fw_name
                    )

                    df.to_excel(
                        writer,
                        index=False,
                        sheet_name=sheet_name
                    )

                    ws = writer.sheets[sheet_name]
                    for col in ws.columns:
                        max_len = max(
                            len(str(cell.value))
                            if cell.value is not None else 0
                            for cell in col
                        )
                        ws.column_dimensions[
                            col[0].column_letter
                        ].width = min(max_len + 4, 50)

            console.print(
                f"[green]  Compliance map: "
                f"{xlsx_path}[/green]"
            )
            return str(xlsx_path)

        except Exception as e:
            console.print(
                f"[red]  Compliance map failed: "
                f"{e}[/red]"
            )
            return None

    # ------------------------------------------------------------------ #
    # OUTPUT 3 -- EXECUTIVE SUMMARY
    # ------------------------------------------------------------------ #

    def generate_executive_summary(
        self,
        aggregated: AggregatedFindings,
        frameworks: list[str],
        org_type:   str
    ) -> str:
        """
        Generate plain English executive summary.
        Ollama generates narrative grounded in KB context.
        Falls back to template if Ollama fails.
        Written for CEO/board not security engineers.
        """
        console.print(
            "[cyan]  Generating executive summary...[/cyan]"
        )

        # Load up to 2 KB files for context
        kb_context = ""
        for fw in frameworks[:2]:
            kb_path = FRAMEWORK_KB_MAP.get(fw)
            if kb_path:
                content = _load_kb_file(kb_path)
                kb_context += content[:1500]

        top_findings    = aggregated.findings[:5]
        findings_summary = "\n".join([
            f"- {f.severity_label}: {f.title}"
            for f in top_findings
        ])

        try:
            prompt = f"""
You are a senior security consultant writing an executive
summary for a board presentation. Plain English only.
No technical jargon. Focus on business risk and impact.

Organization type: {org_type.replace('_', ' ').title()}
Target: {self.target}
Total findings: {aggregated.total_findings}
Critical: {aggregated.critical_count}
High: {aggregated.high_count}
Medium: {aggregated.medium_count}
Low: {aggregated.low_count}
Zero day flags: {aggregated.zero_day_count}

Top findings:
{findings_summary}

Frameworks assessed:
{', '.join(FRAMEWORK_NAMES.get(f, f) for f in frameworks)}

Write a 3 paragraph executive summary:
Paragraph 1: Overall risk posture in business terms
Paragraph 2: Most critical findings and business impact
Paragraph 3: Top 3 recommended actions with priority

Under 300 words. Written for a CEO not an engineer.
"""
            result: LLMResponse = query_llm(
                prompt=prompt,
                system_prompt=(
                    "You are a senior security consultant. "
                    "Write clear concise executive summaries. "
                    "No bullet points. No jargon. "
                    "Plain English paragraphs only."
                ),
                expect_json=False
            )

            if result and result.content:
                content = result.content
                if (
                    isinstance(content, str) and
                    len(content) > 50
                ):
                    console.print(
                        "[green]  Executive summary: "
                        "Ollama[/green]"
                    )
                    return content

        except Exception as e:
            console.print(
                f"[yellow]  Ollama summary failed: "
                f"{e} -- template fallback[/yellow]"
            )

        console.print(
            "[dim]  Executive summary: template[/dim]"
        )
        return self._template_summary(aggregated, frameworks)

    def _template_summary(
        self,
        aggregated: AggregatedFindings,
        frameworks: list[str]
    ) -> str:
        """Template fallback when Ollama unavailable."""
        fw_names = ", ".join(
            FRAMEWORK_NAMES.get(f, f) for f in frameworks
        )

        risk_level = "LOW"
        if aggregated.critical_count > 0:
            risk_level = "CRITICAL"
        elif aggregated.high_count > 2:
            risk_level = "HIGH"
        elif aggregated.medium_count > 3:
            risk_level = "MEDIUM"

        zero_day_note = ""
        if aggregated.zero_day_count > 0:
            zero_day_note = (
                f" {aggregated.zero_day_count} finding(s) "
                f"were flagged as potential zero day "
                f"vulnerabilities with no existing CVE match. "
                f"Raw evidence preserved."
            )

        nerc_note = ""
        if "nerc_cip" in frameworks and aggregated.critical_count > 0:
            nerc_note = (
                f"\n\nNERC CIP COMPLIANCE NOTE: This assessment "
                f"identified {aggregated.critical_count} critical "
                f"finding(s) with direct NERC CIP control mappings. "
                f"NERC CIP violations carry financial penalties of up "
                f"to $1,000,000 per violation per day. Immediate "
                f"remediation is required to maintain compliance and "
                f"avoid regulatory exposure. All NERC CIP control "
                f"gaps are documented in the accompanying compliance "
                f"map with applicable standard references."
            )

        return (
            f"R3D conducted an autonomous security assessment "
            f"of {self.target}. Overall risk posture: "
            f"{risk_level}. Total findings: "
            f"{aggregated.total_findings}."
            f"{zero_day_note}\n\n"
            f"Assessment identified "
            f"{aggregated.critical_count} critical, "
            f"{aggregated.high_count} high, "
            f"{aggregated.medium_count} medium, "
            f"{aggregated.low_count} low severity findings. "
            f"All findings mapped to {fw_names}.\n\n"
            f"Immediate priorities: critical findings within "
            f"24 hours, high within 30 days, medium within "
            f"90 days. Full remediation guidance in the "
            f"accompanying risk register."
            f"{nerc_note}"
        )


    # ------------------------------------------------------------------ #
    # MAIN RUN
    # ------------------------------------------------------------------ #

    def run(
        self,
        aggregated: AggregatedFindings,
        profile,
    ) -> dict:
        """
        Execute GRC mapping.
        Reads org_type from profile if saved -- skips menu.
        Each output independent -- one failure never stops others.
        """
        console.print(
            f"\n[bold cyan]"
            f"{'='*52}\n"
            f"  R3D GRC MAPPER\n"
            f"  Target   : {self.target}\n"
            f"  Findings : {aggregated.total_findings}\n"
            f"{'='*52}"
            f"[/bold cyan]\n"
        )

        # Step 1 -- Org type
        saved_org_type = getattr(profile, "org_type", None)
        self.org_type  = self.select_org_type(saved_org_type)

        # Save to profile for resume support
        try:
            profile.org_type = self.org_type
        except Exception:
            pass

        # Step 2 -- AI surface detection
        ai_surfaces = getattr(profile, "ai_surfaces", [])
        has_ai      = len(ai_surfaces) > 0
        if has_ai:
            console.print(
                f"[dim]  AI surfaces: "
                f"{len(ai_surfaces)} found[/dim]"
            )

        # Step 3 -- Load frameworks
        self.frameworks = self.load_frameworks(
            self.org_type, has_ai
        )

        if not self.frameworks:
            console.print(
                "[red]  No frameworks loaded -- "
                "check data/compliance_kb/[/red]"
            )
            return {}

        console.print(
            f"[green]  Frameworks: "
            f"{len(self.frameworks)} loaded[/green]"
        )

        results = {}

        # Step 4 -- Risk register
        try:
            rr = self.generate_risk_register(
                aggregated, self.frameworks
            )
            if rr:
                results["risk_register"] = rr
        except Exception as e:
            console.print(
                f"[red]  Risk register crashed: {e}[/red]"
            )

        # Step 5 -- Compliance map
        try:
            cm = self.generate_compliance_map(
                aggregated, self.frameworks
            )
            if cm:
                results["compliance_map"] = cm
        except Exception as e:
            console.print(
                f"[red]  Compliance map crashed: {e}[/red]"
            )

        # Step 6 -- Executive summary
        try:
            summary = self.generate_executive_summary(
                aggregated, self.frameworks, self.org_type
            )
            results["executive_summary"] = summary
            console.print(
                "[green]  Executive summary: done[/green]"
            )
        except Exception as e:
            console.print(
                f"[red]  Executive summary crashed: "
                f"{e}[/red]"
            )
            results["executive_summary"] = (
                self._template_summary(
                    aggregated, self.frameworks
                )
            )

        console.print(
            f"\n[bold green]"
            f"{'='*52}\n"
            f"  GRC MAPPING COMPLETE\n"
            f"  Org type  : {self.org_type}\n"
            f"  Frameworks: {len(self.frameworks)}\n"
            f"  Outputs   : {len(results)}\n"
            f"{'='*52}"
            f"[/bold green]\n"
        )

        return results


# ------------------------------------------------------------------ #
# TEST
# ------------------------------------------------------------------ #
if __name__ == "__main__":
    console.print(
        "[bold green]R3D GRC Mapper -- "
        "Module Load Test[/bold green]\n"
    )

    aggregator = FindingsAggregator(target="example.com")
    aggregator.add_findings([
        Finding(
            title="Prompt injection confirmed",
            description="LLM vulnerable to direct injection",
            finding_type="prompt_injection",
            source_module="llm_attack",
            target="example.com"
        ),
        Finding(
            title="Port 22 SSH exposed",
            description="SSH on default port",
            finding_type="exposed_port",
            source_module="traditional_recon",
            target="example.com"
        ),
        Finding(
            title="CSP header missing",
            description="No Content-Security-Policy",
            finding_type="header_missing",
            source_module="traditional_recon",
            target="example.com"
        ),
    ])

    aggregated = aggregator.aggregate()

    class MockProfile:
        org_type    = None
        ai_surfaces = []

    mapper  = GRCMapper(
        target="example.com",
        mode="SEMI-AUTO"
    )

    results = mapper.run(aggregated, MockProfile())

    console.print(f"\nOutputs: {len(results)}")
    for key, val in results.items():
        if key != "executive_summary":
            console.print(f"  {key}: {val}")
        else:
            console.print(
                f"  executive_summary: {len(val)} chars"
            )
    console.print(
        "[green]Module loaded successfully.[/green]"
    )